
###

POST http://localhost:5000/pl/list HTTP/1.1
content-type: application/json

{
    "name": "",
    "desc": "流水线"
}

### 任务列表
POST http://localhost:5000/task/list HTTP/1.1
content-type: application/json

{
    "code": "rename"
}

###
POST http://localhost:5000/task/list HTTP/1.1
content-type: application/json

{
}
### 运行任务
POST http://localhost:5000/task/start HTTP/1.1
content-type: application/json

{
    "code": "find"
}

### 运行流水线
POST http://localhost:5000/pl/exec HTTP/1.1
content-type: application/json

{
    "id": "PL002"
}

### 运行任务
POST http://localhost:5000/all/save HTTP/1.1
content-type: application/json

{
}